Repository monnani-girl/nomonnani-FE, pull requests merged in 2023-06, with the labels that each got.

#108 feat: Error component 적용 - #107
  src/components/Error.tsx
  src/index.tsx
  src/pages/home.tsx
  src/pages/select.tsx
Labels: 리팩토링, 기능

#109 style: 선택 페이지 이전 버튼 비활성화 - #102
  src/components/ImageUpload.tsx
  src/pages/select.tsx
Labels: 스타일

#111 feat: useCountUp hooks 생성 - #110
  src/hooks/useCountUp.ts
  src/pages/home.tsx
Labels: 기능, 스타일

#104 refactor: 결과 페이지 QA 수정 내용 - #103
  src/pages/home.tsx
  src/pages/result.tsx
  src/style/color.css
  src/style/global.tsx
Labels: 리팩토링, 스타일

#112 v2.1.0 배포
  src/api/index.ts
  src/api/types.ts
  src/components/Error.tsx
  src/components/Header.tsx
  src/components/ImageUpload.tsx
  src/components/Loading.tsx
  src/components/SelectItems.tsx
  src/hooks/useCountUp.ts
  src/index.tsx
  src/pages/home.tsx
  src/pages/result.tsx
  src/pages/select.tsx
  src/style/color.css
  src/style/global.tsx
Labels: 배포
