Repository monnani-girl/nomonnani-FE, pull requests merged in 2023-05, with the labels that each got.

#79 design: font-weight 수정 작업
  src/App.tsx
  src/pages/result.tsx
  src/style/global.tsx
Labels: 리팩토링, 스타일

#66 test: GA 테스트 코드 추가
  package-lock.json
  package.json
  src/components/RouteChangeTracker.tsx
  src/components/router.tsx
  src/index.tsx
  src/pages/home.tsx
Labels: 기능

#82 docs: Update README.md
  README.md
Labels: 문서

#84 chore: 오타 수정
  src/static/quote.ts
Labels: 버그수정

#87 fix: 이미지 저장 링크 변경 - #85
  src/pages/result.tsx
Labels: 리팩토링, 버그수정

#88 feat: 결과 API 변경 대응 및 프론트 static 파일 제거 - #86
  src/api/types.ts
  src/pages/result.tsx
  src/static/product.ts
  src/static/quote.ts
Labels: API

#89 v2.0.0 배포
  README.md
  package-lock.json
  package.json
  src/api/types.ts
  src/assets/images.d.ts
  src/assets/loading.gif
  src/assets/results/broccoli1.png
  src/assets/results/broccoli2.png
  src/assets/results/broccoli3.png
  src/assets/results/cabbage1.png
  src/assets/results/cabbage2.png
  src/assets/results/cabbage3.png
  src/assets/results/carrot1.png
  src/assets/results/carrot2.png
  src/assets/results/carrot3.png
  src/assets/results/potato1.png
  src/assets/results/potato2.png
  src/assets/results/potato3.png
  src/assets/results/pumpkin1.png
  src/assets/results/pumpkin2.png
  src/assets/results/pumpkin3.png
  src/assets/results/tangerine1.png
  src/assets/results/tangerine2.png
  src/assets/results/tangerine3.png
  src/components/Header.tsx
  src/components/ImageUpload.tsx
  src/components/Loading.tsx
  src/components/Modal.tsx
  src/components/RouteChangeTracker.tsx
  src/components/SelectItem.tsx
  src/components/SelectItems.tsx
  src/components/router.tsx
  src/index.tsx
  src/pages/home.tsx
  src/pages/result.tsx
  src/pages/select.tsx
  src/static/image.ts
  src/static/product.ts
  src/static/quote.ts
  src/static/select.ts
  src/style/global.tsx
Labels: 배포

#91 feat: 방문자수 카운팅 추가 - #90
  src/api/index.ts
  src/api/types.ts
  src/pages/home.tsx
Labels: 기능, API

#101 design: 로딩페이지 UX Writing 수정 - #100
  src/components/Loading.tsx
Labels: 리팩토링, 스타일

#98 design: 문답 페이지 사이즈 축소 - #97
  src/components/SelectItems.tsx
  src/pages/select.tsx
Labels: 리팩토링, 스타일

#106 chore: Header icon 수정 - #105
  src/components/Header.tsx
Labels: 리팩토링, 스타일

#96 design: 랜딩 페이지 상단 마진 수정 - #94
  src/pages/home.tsx
Labels: 리팩토링, 스타일

#99 refactor: 이미지 업로드 UX Writing & 배율 수정 - #95
  src/components/ImageUpload.tsx
  src/pages/select.tsx
Labels: 리팩토링, 스타일, 버그수정
